# Generated by Django 2.2.16 on 2022-08-11 08:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Введите название произведения",
                        verbose_name="Название произведения",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Укажите год выпуска",
                        validators=[
                            django.core.validators.MinValueValidator(-10000),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                        verbose_name="Год выпуска",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Укажите категорию",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="reviews.Category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Название произведения",
                "verbose_name_plural": "Названия произведений",
            },
        ),
    ]
