# Generated by Django 2.2.16 on 2022-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_auto_20220814_1230"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="description",
            field=models.TextField(
                help_text="Напишите отзыв",
                null=True,
                verbose_name="Текст отзыва",
            ),
        ),
    ]
