# Generated by Django 2.2.16 on 2022-08-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_title_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                help_text="Произведение",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.Title",
                verbose_name="Произведение",
            ),
        ),
    ]
