# Generated by Django 2.2.16 on 2022-08-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenreTitle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.Genre",
                        verbose_name="Жанр",
                    ),
                ),
                (
                    "title_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.Title",
                        verbose_name="Название произведения",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                help_text="Укажите жанр",
                through="reviews.GenreTitle",
                to="reviews.Genre",
                verbose_name="Жанр",
            ),
        ),
    ]
