# Generated by Django 2.2.16 on 2022-08-11 08:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("reviews", "0004_genre_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Напишите отзыв", verbose_name="Текст отзыва"
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время публикации отзыва (автоматическое поле)",
                        verbose_name="Дата и время публикации отзыва",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        help_text="Поставьте оценку",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор отзыва (автоматическое поле)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.User",
                        verbose_name="Автор отзыва",
                    ),
                ),
                (
                    "title_id",
                    models.ForeignKey(
                        help_text="Произведение",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.Title",
                        verbose_name="Произведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("author", "title_id"), name="author_title"
            ),
        ),
    ]
