# Generated by Django 2.2.16 on 2022-08-11 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("reviews", "0005_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Напишите комментарий",
                        verbose_name="Текст комментария",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время публикации комментария (автоматическое поле)",
                        verbose_name="Дата и время публикации комментария",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор комментария (автоматическое поле)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="users.User",
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "review_id",
                    models.ForeignKey(
                        help_text="Укажите комментируемый отзыв",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.Review",
                        verbose_name="Отзыв",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
