# Generated by Django 2.2.16 on 2022-08-23 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_review_score_positivesmallinteger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.SmallIntegerField(
                help_text="Укажите год выпуска",
                validators=[
                    django.core.validators.MinValueValidator(-2500),
                    django.core.validators.MaxValueValidator(2050),
                ],
                verbose_name="Год выпуска",
            ),
        ),
    ]
